name: Scan images with trivy
on:
  workflow_dispatch:

jobs:
  scan:
    name: Scan cluster using trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "mockserver/mockserver"
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: "${{github.workspace}}/trivy-k8s-report.sarif"

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-k8s-report
          path: 'trivy-results.sarif'

      - name: uload sarif report to github
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
